### ISSUE TITLE
Feature Request: Ignore track matching %title%

### ISSUE THREAD

**Issue by CultofRobots** [gix/foo_scrobble#11]
I would love if the component could automatically skip scrobbling tracks matching certain title strings (like "Untitled").

**Comment by apometron** [comment]
Or maybe "Unknown  Artist", like one torrent I found with two tracks like this. =((((

Would be nice!!! =DDD

It would save space on my hard drive....

**Comment by gix** [comment]
This is already possible. Scrobble settings allow you to set a skip format. A track is skipped when that titleformat evaluates to non-empty, e.g. `$if($strstr(%title%,Untitled),1,)` would skip titles containing `Untitled`. See foobar's title formatting help for further info.

**Comment by CultofRobots** [comment]
Great! I assumed skip format was used for codec. My mistake.
