### ISSUE TITLE
Scrobbling stopped working

### ISSUE THREAD

**Issue by mopihu** [gix/foo_scrobble#13]
Scrobbling has stopped working a few weeks ago. Console says that it needs to reauth:
`foo_scrobble: Scrobbling failed (error: 9, Invalid session key. Please re-authenticate.)`

But after reauthenticating, it still does not scrobble:
`foo_scrobble: Queuing scrobble (Unauthenticated)`

**Comment by gix** [comment]
How do you re-auth? What does the log say? It should log the different steps you do to acquire a new session key.

**Comment by mopihu** [comment]
By clicking the clicking the clear/request authorization button in the component's settings page.

I just read on the forum thread somebody saying that downgrading to 1.1.0 fixed it for them, so I tried it, but it didn't work for me. However, after switching back to 1.3.1, now it seems to be working again. So I guess you can close this for now, I'll let you know if it stops working again.

And thanks again for this awesome plugin, really appreciate it.

Cheers!

**Comment by s-a-b** [comment]
@gix hello, it seems foo_scrobble does not scrobble at foobar 1.4.8
Thanks for the great dll, though it needs update to fix the issue.

**Comment by mtasker** [comment]
Just wanted to leave a comment for anyone else who finds this via search - I had the same issue; to finalize the authorization I had to click "Apply" in the preferences window after I clicked Complete authorization. Once I did that, all my cached tracks were submitted.

**Comment by gix** [comment]
> I had to click "Apply" in the preferences window

Most preference pages are this way. Any changes you do must be persisted by clicking either OK or Apply. This allows you to cancel any changes you made if you decide otherwise.
