### ISSUE TITLE
Scrobbling does not work at all, possible token issue

### ISSUE THREAD

**Issue by Ardakilic** [gix/foo_scrobble#17]
Hello, I've been using this plugin without issues for a while, but recently I started to get an error (can't remember since when because I wasn't checking the logs and last.fm apparently).

I get this:

```
foo_scrobble: Scrobbling failed (error: 9, Please re - authenticate.)
```

And after each track I get this on console:

```
foo_scrobble: Queuing scrobble (Unauthenticated)
```

Even though I allow access / re-quthorize successfully.

Here's what happens when I clear authorization and re-authorize from the panel on the console:

```
foo_scrobble: Requesting auth token
foo_scrobble: Received auth token: token_goes_here
foo_scrobble: Requesting session key
foo_scrobble: New session key: session_key_goes_here
```

I use Firefox as a browser as my default browser to request token, if that would matter.

And when I start the app, I get this:

```
foo_scrobble: Scrobbling failed (error: 9, Please re - authenticate.)
```

I'd appreciate if this could be investigated. I'm using version 1.3.1.

Thanks in advance,

**Comment by gix** [comment]
I may have identified a bug in the settings dialog. Could you please verify by repeating the following two scenarios:

First:
1. Open the foo_scrobble settings page.
2. Click `Clear authorization`
3. Do the request + complete authorization steps.
4. The `Apply` button at the bottom should be *disabled*.
5. Close the settings.
6. Scrobbling should fail.

Now repeat:
1. Open the foo_scrobble settings page.
2. Click `Clear authorization`
3. **Click `Apply`**
3. Do the request + complete authorization steps.
3. **Click `Apply`**
5. Close the settings.
6. Scrobbling should succeed.

**Comment by Ardakilic** [comment]
@gix Indeed, can confirm, this worked nicely! I can now see now playing on my last.fm profile! 

Thanks again for maintaining this plugin and the debug process!

**Comment by drook** [comment]
> 
> 
> I may have identified a bug in the settings dialog. Could you please verify by repeating the following two scenarios:
> 
Jeez, you save my day. Thanks, man.

**Comment by darekkay** [comment]
I confirm, this solved the issue for me as well 🚀  
Interestingly, I was missing the scrobbles for the last 5 days, but they all appeared in last.fm after reauthorizing.

**Comment by gix** [comment]
> Interestingly, I was missing the scrobbles for the last 5 days, but they all appeared in last.fm after reauthorizing.

That's because all scrobbles are cached internally in case they cannot be submitted right away (due to network outage, offline use, authentication problems, …).
