### ISSUE TITLE
TTA embedded cussheet causes duplicate scrobbls

### ISSUE THREAD

**Issue by Soulcrzkc** [gix/foo_scrobble#18]
foobar 1.5.5 
file: 発熱巫女～ず - ''Everflowering'' Masterpieces of Hatsunetsumiko's 2011 - 2013.tta
(I don't know if it will cause any problem, but i will give the files for you to test)
https://mega.nz/folder/8llHQSQB#YbhptauVaJWNsZmlOa5hQA
When I use cue file, it works well. But if I embed cuesheet in the tta file and open the tta file, foobar will scrobble it every second.
like this.
![tta](https://user-images.githubusercontent.com/15704468/92205722-d600ef00-eeb8-11ea-8b5d-74ef01d0fd14.png)
And foobar will send error album artist.
error
https://www.last.fm/zh/music/%E9%99%BD%E8%8A%B1/%27Everflowering%27+Masterpieces+of+Hatsunetsumiko%27s+2011+-+2013
it should be
https://www.last.fm/zh/music/%E7%99%BA%E7%86%B1%E5%B7%AB%E5%A5%B3%EF%BD%9E%E3%81%9A/%27Everflowering%27+Masterpieces+of+Hatsunetsumiko%27s+2011+-+2013

How can I solve this problem? Thanks

PS:
I have tried to use other tta files, they repeated those problems.

**Comment by gix** [comment]
This seems to be a bug in ` foo_input_tta`. When playing such a TTA file, the "dynamic info track" event is continuously emitted, even though the artist/title hasn't changed.
