### ISSUE TITLE
Punctuation conversions One Dot Leader vs full stop

### ISSUE THREAD

**Issue by joetting** [gix/foo_scrobble#19]
My tags are stored in ID3v2 version 2.3.
should be:
https://www.last.fm/music/R.E.M.
actual:
https://www.last.fm/music/R%E2%80%A4E%E2%80%A4M%E2%80%A4
Resulting in incorrect artist
I am not sure how I can solve this on my end.

**Comment by gix** [comment]
foo_scrobble doesn't do any text conversions, it just asks foobar2000 to format `[%artist%]` for the current song (see `Help > Title formatting help`). So it seems as if your tags are "broken".

**Comment by joetting** [comment]
Thanks!  My working solution:
[$replace(%album artist%,'․','.')]
