### ISSUE TITLE
Scrobbles not caching

### ISSUE THREAD

**Issue by jumperkballs** [gix/foo_scrobble#28]
Hi.

Using latest release version of the plugin with the latest stable version of foobar in portable mode.

Plugin appears to either not be caching scrobbles or cached scrobbles are not being accepted by last.fm. I made a post on the official last.fm support forum as it does appear as if the website and API are having connectivity issues but their QA director suggested I make a post here.

If there are any troubleshooting steps I can take please let me know.

Thanks!

**Comment by gix** [comment]
What does the log in foobar's Console (View -> Console) show regarding foo_scrobble?

Tracks aren't scrobbled directly, but always written to the cache, and only removed again after last.fm accepts the submission (or if the submitted track has invalid tags and resubmission would fail again). These cases should all be visible in the log.

**Comment by jumperkballs** [comment]
Everything's been scrobbling fine the last couple of days. Last.FM was having major connectivity issues that day and I think their QA director was just trying to pass the buck as he kept unlisting tickets related to songs not scrobbling. Sorry for the irrelevant ticket.

For the next time last.fm is having issues: is the cache persistent between sessions or do I need to leave foobar running until the submissions are accepted? Thanks!

**Comment by gix** [comment]
> is the cache persistent between sessions or do I need to leave foobar running until the submissions are accepted

The cache is indeed persistent, so you can safely close foobar.
