### ISSUE TITLE
cant build

### ISSUE THREAD

**Issue by KrenarShabani** [gix/foo_scrobble#29]
"C:\Users\k\Downloads\foo_scrobble-master\foo_scrobble-master\build.proj" (default target) (1) ->
       "C:\Users\k\Downloads\foo_scrobble-master\foo_scrobble-master\src\foo_scrobble.sln" (Build target) (2:2) ->
       "C:\Users\k\Downloads\foo_scrobble-master\foo_scrobble-master\src\foo_scrobble\foo_scrobble.vcxproj.metaproj" (default target) (3:2) ->
       "C:\Users\k\Downloads\foo_scrobble-master\foo_scrobble-master\src\foo_scrobble\foo_scrobble.vcxproj" (default target) (8:2) ->
       (ClCompile target) ->
         cl : command line error D8004: '/pathmap:' requires an argument [C:\Users\k\Downloads\foo_scrobble-master\foo_scrobble-master\src\foo_scro
       bble\foo_scrobble.vcxproj]

**Comment by gix** [comment]
Did you clone the repository with git or downloaded an archive with the source? Pathmap being empty points to the former which is currently not supported.
