### ISSUE TITLE
Bug with the title of the musics

### ISSUE THREAD

**Issue by apometron** [gix/foo_scrobble#3]
See:

https://i.imgur.com/cJlmQ6P.png

And this:

https://i.imgur.com/YEh6FTx.png

Do you see what I mean?

The track appear two times but it is not definitive...

The second scrobble stays wrong for some seconds...

Could you solve it, please??? =))))

**Comment by gix** [comment]
The "Now playing notification" entry (with "Scrobbling now" behind it) is only sent once you have listened to a song for at least 3 seconds so that skipping through tracks does not send one for each track. This is intended behavior.
