### ISSUE TITLE
Now Playing notification's album shows Artist instead of Album Artist

### ISSUE THREAD

**Issue by PlaylistsTrance** [gix/foo_scrobble#38]
When listening to a track, the track artist shows up as album artist on last.fm's now playing, but is scrobbled correctly with the album artist. So instead of Various Artists: Some Album, the album in now playing shows up as Track Artist: Some Album.

The relevant field mappings are:
```
Artist: $if2([%lastfm artist%],[%artist%])
Album Artist: $if2([%lastfm albumartist%],[%album artist%])
```
The audio file does not contain the custom lastfm tags, so %artist% and %album artist% are used.

**Comment by gix** [comment]
This seems like a bug on last.fm's side. Does this work with anything else? The data sent by foo_scrobble is the same for Now Playing and scrobbling, and both times the `albumArtist` field is set correctly. I also don't see any `corrected` info in the response returned by last.fm.

**Comment by PlaylistsTrance** [comment]
My apologies, I should have checked other scrobblers first. It looks like you're correct, as web scrobbler and Spotify have the same problem.
