### ISSUE TITLE
Submit foo_scrobble to foobar2000.org/components

### ISSUE THREAD

**Issue by MenaceInc** [gix/foo_scrobble#39]
[Process for getting a component listed in the components section of the foobar2000 site](https://hydrogenaud.io/index.php/topic,82691.0.html).

Basic process is ask a staff member for access.

Would help a lot with visibility and would make it easier to remember the plugin when I inevitably have to reinstall Windows at some point.

**Comment by gix** [comment]
I asked a long time ago and never received a response. Maybe I should try again.

**Comment by MenaceInc** [comment]
Definitively deserves the recognition.

**Comment by Barough** [comment]
> I asked a long time ago and never received a response. Maybe I should try again.

Contact Peter Pawlowski (foobat2000 Author)
https://hydrogenaud.io/index.php?action=profile;u=84

**Comment by gix** [comment]
https://www.foobar2000.org/components/view/foo_scrobble
