### ISSUE TITLE
Can't point specified procedure

### ISSUE THREAD

**Issue by Dimsok** [gix/foo_scrobble#4]
Failed to load DLL: Reason: Не найдена указанная процедура (can't point specified procedure).

**Comment by gix** [comment]
If I read that message right, then in English it is the "The specified procedure could not be found". Which means all DLLs are present, but at least one of them is missing a procedure.

To diagnose which one is missing, could you please download the latest `Dependencies.zip` from https://github.com/lucasg/Dependencies/releases and then open `foo_scrobble.dll` and look for red entries in the top right list.

**Comment by Dimsok** [comment]
Win XP

**Comment by gix** [comment]
Windows XP is not supported, sorry.
