### ISSUE TITLE
Getting some weird login error

### ISSUE THREAD

**Issue by parasiteoflife** [gix/foo_scrobble#51]
In searching for the cause of a delay I'm getting randomly when playing songs I found this in the console (there are similar messages for every song):

```
last.fm Error: Login: User required to be logged in
Found 0 scrobbles in last.fm of "WWWWW"
```

And is wrong for 2 reasons, the obvious one that I'm actually logged in (or authorized in) and the second is that the song doesn't have 0 scrobbles, if that means my own scrobbles then is wrong, if it means global scrobbles then is also wrong. And this not only happens with that one song, it happens with every single one, I can see messages like these ones too:

```
Found 0 scrobbles in last.fm (since last known scrobble at 2022-07-15 15:58:38) of "XXXXXXX"
Found 0 scrobbles in last.fm (since last known scrobble at 2021-01-19 20:34:50) of "YYYYYYY"
```

Which are also wrong, I don't know from where it takes the date but it's not true, for example in this case both of those songs were scrobbled in the past week.

When the songs end I can see in my last.fm profile that the songs were scrobbled.

**Comment by gix** [comment]
All messages from foo_scrobble start with "foo_scrobble: ", so these messages are from another extension.

**Comment by parasiteoflife** [comment]
> All messages from foo_scrobble start with "foo_scrobble: ", so these messages are from another extension.

You are right, I thought this was the only extension that used last.fm I had, turns out foo_enhanced_playcount was the one failing, I totally forgot it imported from last.fm.
Sorry, will close this.
