### ISSUE TITLE
I can't disable scrobbling

### ISSUE THREAD

**Issue by kayodde** [gix/foo_scrobble#54]
In the context menu I want to set "enable scrobbling" to disabled and when I do that it doesn't turn it off, it continues scrobbling regardless, I have to clear authorisation to get it to stop. Disabling in configure doesn't work either.
Is this expected behaviour?

**Comment by gix** [comment]
If you turn it off mid-track it still scrobbles the currently playing track. The next track won't be scrobbled.

**Comment by lopes143** [comment]
It happens to me too. Even starting foobar with the option turned off still scrobbles.
