### ISSUE TITLE
Setting for "Send Now Playing notification" is not working

### ISSUE THREAD

**Issue by Jeddix** [gix/foo_scrobble#9]
The configuration setting for "Send Now Playing notification" is not working. It doesn't matter if I check the box or not, the scrobbler will always send the notifcations.

It seems that you set `EnableNowPlaying` in the config but you are then not using it in the `PlaybackScrobbler` class. `ShouldSendNowPlaying()` should check for this setting first.

**Comment by gix** [comment]
Indeed, thanks for spotting this. Fixed in [v1.3.1](https://github.com/gix/foo_scrobble/releases/tag/v1.3.1).
